const BASE = 'http://localhost:3000';
let token = '';
const headers = () => ({ 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token });
async function login() { const r = await fetch(`${BASE}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'admin', password: '1234' }) }); const d = await r.json(); token = d.token; }
async function addTopic(name) { const r = await fetch(`${BASE}/api/topics`, { method: 'POST', headers: headers(), body: JSON.stringify({ name }) }); const d = await r.json(); console.log('📁', name); return d.id; }
async function addQ(topicId, q, a) { await fetch(`${BASE}/api/questions`, { method: 'POST', headers: headers(), body: JSON.stringify({ topicId, question: q, answer: a }) }); }

async function run() {
  await login();

  // QIB Project
  let id = await addTopic('QIB Project');
  await addQ(id, "Difference between pseudo class and pseudo elements?", "Pseudo-class:\n• Targets an element based on its STATE.\n• Starts with a single colon (:).\n• Examples: :hover, :focus, :active, :nth-child(2), :first-child\n• Usage: button:hover { color: red; }\n\nPseudo-element:\n• Styles a specific PART of an element or inserts content.\n• Starts with a double colon (::) (CSS3 standard).\n• Examples: ::before, ::after, ::first-line, ::placeholder\n• Usage: p::first-line { font-weight: bold; }");
  await addQ(id, "What is Event propagation and examples", "Event propagation is the order in which events are fired when an element is clicked (or triggered) inside other nested elements.\n\nTwo phases:\n1. Capturing Phase (Trickling down): Window → Document → HTML → Body → Parent → Target.\n2. Bubbling Phase (Bubbling up): Target → Parent → Body → HTML → Document → Window.\n\nBy default, event handlers execute in the Bubbling phase.\nYou can stop propagation using: event.stopPropagation();");
  await addQ(id, "What is async and await?", "async/await is syntax sugar over Promises, making async code look synchronous.\n\n• async: Keyword placed before a function makes it return a Promise.\n• await: Pauses execution until the Promise resolves or rejects (can only be used inside async functions).\n\nExample:\nasync function fetchData() {\n  try {\n    const response = await fetch('/api/data');\n    const data = await response.json();\n    console.log(data);\n  } catch (err) {\n    console.error(err);\n  }\n}");
  await addQ(id, "Define flex-direction and default", "flex-direction defines the main axis along which flex items are placed in the flex container.\n\nValues:\n• row (DEFAULT): Items placed horizontally (left to right)\n• row-reverse: Items placed horizontally (right to left)\n• column: Items placed vertically (top to bottom)\n• column-reverse: Items placed vertically (bottom to top)");
  await addQ(id, "Difference between grid and flex", "CSS Flexbox:\n• 1-Dimensional layout system.\n• Deals with layout in either rows OR columns (one at a time).\n• Content-first approach.\n• Best for: aligning items, navbars, small-scale layouts.\n\nCSS Grid:\n• 2-Dimensional layout system.\n• Deals with BOTH rows and columns simultaneously.\n• Layout-first approach (define grid, then place items).\n• Best for: complex page layouts, dashboards, galleries.");
  await addQ(id, "What is querySelector and querySelectorAll?", "Both are modern DOM selection methods using CSS selectors.\n\nquerySelector():\n• Returns the FIRST element that matches the selector.\n• document.querySelector('.card')\n\nquerySelectorAll():\n• Returns a NodeList (static) of ALL elements that match.\n• document.querySelectorAll('.card')\n• You can loop through the NodeList using .forEach().");
  console.log('  ✅ QIB Project done');

  // RJR
  id = await addTopic('RJR');
  await addQ(id, "How to add style policy in AEM?", "Style System in AEM allows authors to define visual variations of a component without backend changes.\n\nSteps:\n1. Create CSS classes in your ClientLib (e.g., .bg-dark, .text-large).\n2. Go to Template Editor -> Policy icon of a component.\n3. In the 'Styles' tab, add Style Groups and Styles.\n4. Map each Style name (e.g., 'Dark Mode') to your CSS class (.bg-dark).\n5. Authors can now select 'Dark Mode' from the paintbrush icon on the component in the page editor.");
  await addQ(id, "What is the mobile-first approach?", "Mobile-First Approach:\n• Designing and coding the layout for mobile screens first (default CSS).\n• Using media queries (min-width) to scale UP for tablets and desktops.\n\nWhy it's best:\n1. Performance: Mobile browsers don't have to parse complex desktop CSS first.\n2. UX Focus: Forces you to prioritize core content for smaller screens.\n3. Easier scaling: It's easier to add complexity for larger screens than to hide/shrink elements for smaller screens.");
  console.log('  ✅ RJR done');

  // SS
  id = await addTopic('SS');
  await addQ(id, "How do you integrate APIs in JavaScript?", "Methods to integrate APIs:\n\n1. Fetch API (Modern native):\nfetch('/api/users').then(res => res.json()).then(data => console.log(data));\n\n2. Axios (Popular library):\naxios.get('/api/users').then(res => console.log(res.data));\n\n3. XMLHttpRequest (Legacy):\nvar xhr = new XMLHttpRequest();\nxhr.open('GET', '/api/users');\nxhr.onload = function() { console.log(xhr.responseText); };\nxhr.send();");
  await addQ(id, "What is event bubbling?", "Event Bubbling is the process where an event triggered on a specific element 'bubbles up' through its ancestors in the DOM tree.\n\nExample: If you click a <button> inside a <div>, the click event fires on the <button> first, then on the <div>, then the <body>, and so on up to the document root.\n\nUse event.stopPropagation() to prevent it.");
  await addQ(id, "What is destructuring in JavaScript?", "Destructuring allows unpacking values from arrays or properties from objects into distinct variables.\n\nObject Destructuring:\nconst user = { name: 'John', age: 30 };\nconst { name, age } = user;\n\nArray Destructuring:\nconst rgb = [255, 200, 0];\nconst [red, green, blue] = rgb;\n\nBenefits: Cleaner syntax, especially when passing props in React or extracting API response data.");
  await addQ(id, "Difference between position: relative and absolute?", "position: relative;\n• Positioned relative to its NORMAL position in the document flow.\n• Does NOT remove the element from the normal flow (leaves a gap where it would have been).\n• Acts as a positioning context for absolute children.\n\nposition: absolute;\n• Positioned relative to its closest POSITIONED ancestor (non-static).\n• REMOVED completely from the normal document flow (other elements ignore it).\n• Moves along with page scroll.");
  await addQ(id, "Difference between display: none and visibility: hidden?", "display: none;\n• Hides the element completely.\n• Removes the element from the document flow (takes up NO space).\n• Children are also hidden and cannot override this.\n\nvisibility: hidden;\n• Hides the element visually.\n• The element STILL takes up space in the document layout (leaves an empty box).\n• Children can technically override it with visibility: visible.");
  console.log('  ✅ SS done');

  // US Bank
  id = await addTopic('US Bank');
  await addQ(id, "How you write JS code in AEM and explain client Libs?", "In AEM, JS is written and managed via ClientLibs (client libraries).\n\n1. Create a clientlib folder under /apps (cq:ClientLibraryFolder).\n2. Set categories property (e.g., 'usbank.components').\n3. Write JS files inside a js folder.\n4. Create js.txt to manifest/list the load order of your scripts.\n5. Include in HTL using data-sly-use.clientlib and data-sly-call.\n\nClientLibs automatically bundle, minify, and cache the code to optimize page loading.");
  await addQ(id, "In Browser DOM which object is the first parent object?", "The Window Object.\n\n• It represents the browser window/tab.\n• It is the global execution context for JS in the browser.\n• All global variables, functions, and the 'document' object itself are properties of the Window object.\n• Example: document.getElementById is actually window.document.getElementById.");
  await addQ(id, "Difference between JS and jQuery. Why use jQuery?", "JS (JavaScript): Native programming language of the web.\njQuery: A fast, small JS library that simplifies DOM manipulation.\n\nWhy use jQuery?\n• Historically: Solved cross-browser compatibility issues (IE vs Chrome).\n• Easier syntax for AJAX calls ($.ajax).\n• Simplified DOM selection ($('.class') vs document.querySelectorAll).\n• Built-in animations.\n\nNote: Today, modern JS (ES6+) and fetch() have largely made jQuery obsolete for new projects.");
  await addQ(id, "SASS Basics – How it works, tokens, mixins", "SASS (Syntactically Awesome Style Sheets) compiles down to standard CSS.\n\n• Tokens (Variables): $primary-color: #0033a0; Store reusable values.\n• Mixins: Reusable blocks of styles that can take arguments.\n  @mixin flex-center { display: flex; align-items: center; justify-content: center; }\n  .btn { @include flex-center; }\n• Nesting: Cleanly nest child selectors inside parents.\n• Partials/Imports: Break CSS into smaller files (_header.scss) and import them.");
  await addQ(id, "Z-index", "z-index controls the vertical stacking order of elements that overlap.\n\n• Elements with a higher z-index appear IN FRONT of elements with a lower z-index.\n• IMPORTANT: z-index ONLY works on positioned elements (position: relative, absolute, fixed, or sticky) or flex/grid items.\n• Values can be positive, negative, or auto.");
  await addQ(id, "Scenario: 9 cards, accommodate 3 per line", "To wrap 9 cards into rows of 3, use Flexbox or CSS Grid.\n\nUsing Flexbox:\n.container {\n  display: flex;\n  flex-wrap: wrap; /* Allows wrapping to next line */\n  gap: 20px;\n}\n.card {\n  flex: 0 0 calc(33.333% - 20px); /* Takes 1/3 width minus gap */\n}\n\nUsing Grid (Simpler):\n.container {\n  display: grid;\n  grid-template-columns: repeat(3, 1fr);\n  gap: 20px;\n}");
  console.log('  ✅ US Bank done');

  console.log('\n🎉 Batch 4 done!');
}
run().catch(console.error);
