const BASE = 'http://localhost:3000';
let token = '';
const headers = () => ({ 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token });

async function login() {
  const r = await fetch(`${BASE}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'admin', password: '1234' }) });
  const d = await r.json(); token = d.token; console.log('✅ Logged in');
}

async function addTopic(name) {
  const r = await fetch(`${BASE}/api/topics`, { method: 'POST', headers: headers(), body: JSON.stringify({ name }) });
  const d = await r.json(); console.log('📁 Topic:', name, d.id); return d.id;
}

async function addQ(topicId, question, answer) {
  await fetch(`${BASE}/api/questions`, { method: 'POST', headers: headers(), body: JSON.stringify({ topicId, question, answer }) });
}

async function addAccount(name, qas) {
  const id = await addTopic(name);
  for (const qa of qas) { await addQ(id, qa.q, qa.a); }
  console.log(`  ✅ ${qas.length} questions added`);
}

async function run() {
  await login();

  await addAccount('HUMANA Account', [
    { q: "How we write JS and CSS in AEM?", a: "In AEM, JS and CSS are written inside ClientLibs (Client Libraries).\n\n• Create a folder under /apps with property categories\n• Add js.txt and css.txt files listing JS/CSS files\n• Place your .js and .css files inside the folder\n• Include via <sly data-sly-use.clientLib='/libs/granite/sightly/templates/clientlib.html'>\n• Call: <sly data-sly-call=\"${clientLib.all @ categories='your.category'}\" />" },
    { q: "How we call the JS and CSS without .txt?", a: "To call JS/CSS without .txt extension in AEM:\n\n• Use the categories property in clientlib node\n• Reference using HTL: data-sly-call=\"${clientLib.all @ categories='category.name'}\"\n• AEM automatically resolves js.txt and css.txt internally\n• Alternative: Use embed[] or dependencies[] property to include other clientlibs\n• The .txt files (js.txt, css.txt) are just manifest files listing the actual source files" },
    { q: "What is Virtual DOM in React?", a: "Virtual DOM is a lightweight JavaScript representation of the real DOM.\n\nHow it works:\n1. React creates a virtual DOM tree in memory\n2. When state changes, React creates a new virtual DOM\n3. Compares old vs new virtual DOM (diffing algorithm)\n4. Only updates changed elements in the real DOM (reconciliation)\n\nBenefits:\n• Faster updates (batch DOM manipulations)\n• Better performance\n• Declarative UI updates" },
    { q: "Angular and React difference?", a: "Angular vs React:\n\n• Type: Angular is a full framework, React is a library\n• Language: Angular uses TypeScript, React uses JSX\n• DOM: Angular uses real DOM, React uses Virtual DOM\n• Data Binding: Angular has two-way binding, React has one-way\n• Learning Curve: Angular is steeper, React is easier\n• Architecture: Angular uses MVC, React is component-based\n• State Management: Angular has built-in services, React needs Redux/Context\n• CLI: Angular CLI vs Create React App\n• Performance: React is generally faster due to Virtual DOM" },
    { q: "What are CSS Tokens?", a: "CSS Tokens (Design Tokens) are the smallest pieces of a design system.\n\nExamples:\n• Colors: --color-primary: #6c5ce7\n• Font sizes: --font-size-lg: 18px\n• Spacing: --spacing-md: 16px\n• Border radius: --radius: 8px\n\nBenefits:\n• Consistent design across components\n• Easy theme switching\n• Single source of truth\n• Used in SASS variables or CSS custom properties" }
  ]);

  await addAccount('BAT Account', [
    { q: "What is a component and its types?", a: "A component is a reusable, independent piece of UI.\n\nTypes in React:\n• Functional Components: Simple functions returning JSX\n• Class Components: ES6 classes extending React.Component\n\nTypes in AEM:\n• Content Components: Text, Image, Carousel\n• Structure Components: Page, Container\n• Foundation Components: Built-in OOTB components\n• Core Components: Modern reusable components\n• Custom Components: Developer-created components" },
    { q: "What is Virtual DOM?", a: "Virtual DOM is an in-memory representation of the real DOM.\n\n• React keeps a lightweight copy of the actual DOM\n• On state change, a new Virtual DOM tree is created\n• React diffs the old and new trees\n• Only the changed nodes are updated in the real DOM\n• This process is called Reconciliation\n• Results in better performance than direct DOM manipulation" },
    { q: "How does page render with Higher Order Component?", a: "A Higher Order Component (HOC) is a function that takes a component and returns a new enhanced component.\n\nExample:\nfunction withAuth(WrappedComponent) {\n  return function(props) {\n    if (!isAuthenticated) return <Redirect to='/login' />;\n    return <WrappedComponent {...props} />;\n  };\n}\n\nconst ProtectedPage = withAuth(MyPage);\n\nRendering flow:\n1. HOC receives the component\n2. Adds extra logic (auth, data fetching)\n3. Returns enhanced component\n4. React renders the enhanced component" },
    { q: "Purpose of useEffect in React?", a: "useEffect is a React Hook for side effects in functional components.\n\nPurposes:\n• Fetching API data\n• Setting up subscriptions\n• Updating document title\n• Setting timers\n• DOM manipulation\n\nSyntax:\nuseEffect(() => {\n  // side effect code\n  return () => { /* cleanup */ };\n}, [dependencies]);\n\n• Empty array []: Runs once on mount\n• [value]: Runs when value changes\n• No array: Runs on every render" },
    { q: "How to get API URL?", a: "Methods to get/call API URL:\n\n1. Fetch API:\nfetch('https://api.example.com/data')\n  .then(res => res.json())\n  .then(data => console.log(data));\n\n2. Axios:\naxios.get('https://api.example.com/data')\n  .then(res => console.log(res.data));\n\n3. XMLHttpRequest (legacy):\nconst xhr = new XMLHttpRequest();\nxhr.open('GET', 'https://api.example.com/data');\nxhr.send();\n\n4. Environment variables:\nconst API_URL = process.env.REACT_APP_API_URL;" },
    { q: "What is JSX syntax?", a: "JSX (JavaScript XML) allows writing HTML-like syntax in JavaScript.\n\nRules:\n• Must return single parent element\n• Use className instead of class\n• Use camelCase for attributes (onClick, onChange)\n• Self-close tags: <img />, <br />\n• Embed JS expressions with {}\n\nExample:\nconst App = () => (\n  <div className='app'>\n    <h1>{title}</h1>\n    <p>Hello {name}</p>\n    {isLoggedIn && <Dashboard />}\n  </div>\n);" },
    { q: "Why use ReactJS?", a: "Reasons to use ReactJS:\n\n• Virtual DOM for fast rendering\n• Component-based architecture\n• Reusable components\n• One-way data flow\n• Large community & ecosystem\n• JSX makes code readable\n• React Native for mobile apps\n• Easy to learn\n• Strong tooling (DevTools, Create React App)\n• Backed by Meta (Facebook)\n• SEO-friendly with SSR (Next.js)" },
    { q: "What is Unit Testing?", a: "Unit Testing is testing individual units/components of code in isolation.\n\nTools:\n• Jest: JavaScript testing framework\n• React Testing Library: For React components\n• Enzyme: Alternative for React testing\n\nExample:\ntest('adds 1 + 2 to equal 3', () => {\n  expect(sum(1, 2)).toBe(3);\n});\n\nBenefits:\n• Catch bugs early\n• Code confidence\n• Documentation\n• Easier refactoring" },
    { q: "Difference between let vs const?", a: "let vs const:\n\nlet:\n• Can be reassigned\n• Block-scoped\n• Cannot be redeclared in same scope\n• Example: let x = 10; x = 20; ✅\n\nconst:\n• Cannot be reassigned\n• Block-scoped\n• Must be initialized at declaration\n• Objects/arrays can be mutated\n• Example: const x = 10; x = 20; ❌\n• const arr = [1]; arr.push(2); ✅\n\nBoth are NOT hoisted like var." },
    { q: "Explain the CSS Box Model?", a: "The CSS Box Model wraps every HTML element with:\n\n1. Content: The actual text/image content\n2. Padding: Space between content and border\n3. Border: Surrounds the padding\n4. Margin: Space outside the border\n\nTotal width = width + padding-left + padding-right + border-left + border-right\n\nbox-sizing: border-box; includes padding and border in the width.\nbox-sizing: content-box; (default) adds padding and border to width." },
    { q: "Why use Sass?", a: "Sass (Syntactically Awesome Style Sheets) benefits:\n\n• Variables: $primary-color: #6c5ce7;\n• Nesting: Nested selectors for cleaner code\n• Mixins: Reusable style blocks\n• Functions: Custom calculations\n• Partials & Import: Split CSS into files\n• Inheritance: @extend directive\n• Loops: @for, @each, @while\n• Conditionals: @if, @else\n\nResult: More maintainable, DRY, organized CSS" },
    { q: "How to create a component in AEM?", a: "Steps to create an AEM component:\n\n1. Navigate to /apps/project/components/\n2. Create a node of type cq:Component\n3. Add required files:\n   • .content.xml (component definition)\n   • componentName.html (HTL template)\n   • _cq_dialog/.content.xml (author dialog)\n   • clientlibs/ (CSS/JS)\n\n4. Set properties:\n   • jcr:title\n   • componentGroup\n   • sling:resourceSuperType\n\n5. Add to allowed components in page template" },
    { q: "How to update title in a Page?", a: "Ways to update page title in AEM:\n\n1. Page Properties:\n   • Open page > Properties > Title field\n\n2. JCR:\n   • Navigate to /content/site/page/jcr:content\n   • Update jcr:title property\n\n3. HTL:\n   <title>${currentPage.title}</title>\n\n4. Via API:\n   PageManager pm = resourceResolver.adaptTo(PageManager.class);\n   Page page = pm.getPage(path);\n   ModifiableValueMap props = page.getContentResource().adaptTo(ModifiableValueMap.class);\n   props.put('jcr:title', 'New Title');" },
    { q: "How to create a template in AEM?", a: "Creating a template in AEM:\n\n1. Editable Templates (modern):\n   • Go to Tools > Templates\n   • Click Create > Select template type\n   • Define structure, initial content, policies\n   • Enable the template\n\n2. Static Templates (legacy):\n   • Create under /apps/project/templates/\n   • Define sling:resourceType\n   • Set allowedPaths\n   • Create page component\n\nTemplate Structure:\n• structure/jcr:content (locked components)\n• initial/jcr:content (default content)\n• policies/ (component policies)" },
    { q: "How does a page render in AEM?", a: "AEM page rendering flow:\n\n1. Browser sends request\n2. Dispatcher checks cache\n3. If not cached, forwards to AEM Publish\n4. Sling URL decomposition:\n   • Resource path\n   • Selectors\n   • Extension\n5. Sling Resource Resolution finds the resource\n6. Resource type maps to component\n7. HTL/Sightly template renders HTML\n8. ClientLibs inject CSS/JS\n9. HTML response sent to browser\n10. Dispatcher caches the response" }
  ]);

  await addAccount('GSK Account', [
    { q: "How to call and retrieve data from API in React?", a: "Using Fetch API with useEffect:\n\nimport { useState, useEffect } from 'react';\n\nfunction App() {\n  const [data, setData] = useState([]);\n\n  useEffect(() => {\n    fetch('https://api.example.com/data')\n      .then(res => res.json())\n      .then(data => setData(data))\n      .catch(err => console.error(err));\n  }, []);\n\n  return <div>{data.map(item => <p>{item.name}</p>)}</div>;\n}\n\nAlternative: Use Axios or async/await pattern." },
    { q: "What are the commands you used in Git?", a: "Common Git commands:\n\n• git clone <url> — Clone repository\n• git pull — Fetch & merge changes\n• git add . — Stage all changes\n• git commit -m 'message' — Commit changes\n• git push — Push to remote\n• git branch — List branches\n• git checkout -b feature — Create & switch branch\n• git merge branch — Merge branch\n• git stash — Temporarily save changes\n• git log — View commit history\n• git revert <hash> — Undo a commit\n• git cherry-pick <hash> — Apply specific commit" },
    { q: "What coding practices do you follow?", a: "Best coding practices:\n\n• Write clean, readable code\n• Follow DRY principle (Don't Repeat Yourself)\n• Use meaningful variable/function names\n• Write comments for complex logic\n• Follow consistent naming conventions (camelCase, BEM for CSS)\n• Code reviews before merging\n• Write unit tests\n• Use version control (Git)\n• Follow SOLID principles\n• Responsive design (mobile-first)\n• Accessibility (WCAG standards)\n• Performance optimization\n• Use linters (ESLint, Prettier)" },
    { q: "Do you have experience working with JIRA?", a: "Yes, JIRA is used for project management in Agile workflows.\n\nUsage:\n• Creating and managing user stories\n• Sprint planning and tracking\n• Bug tracking and reporting\n• Kanban/Scrum boards\n• Linking stories to Git commits\n• Time tracking and logging\n• Creating epics and sub-tasks\n• Dashboard for project status\n• Filters and JQL queries\n• Integration with Confluence, Bitbucket" },
    { q: "What do you do if you encounter merge conflicts?", a: "Handling merge conflicts:\n\n1. Pull latest changes: git pull origin main\n2. Attempt merge: git merge feature-branch\n3. Git marks conflicts in files with:\n   <<<<<<< HEAD\n   (your changes)\n   =======\n   (incoming changes)\n   >>>>>>> feature-branch\n4. Open conflicted files, review both versions\n5. Choose correct code, remove conflict markers\n6. Test the resolved code\n7. Stage: git add .\n8. Commit: git commit -m 'Resolved merge conflicts'\n9. Push: git push\n\nTools: VS Code merge editor, GitKraken, SourceTree" },
    { q: "How to integrate third-party applications?", a: "Methods to integrate third-party apps:\n\n1. REST APIs: Use fetch/axios to call external APIs\n2. SDKs: Install third-party SDK packages\n3. npm packages: Install via npm install\n4. Script tags: Add external scripts to HTML\n5. iFrames: Embed external content\n6. Webhooks: Event-driven integrations\n\nExample (Google Analytics):\n<script async src='https://www.googletagmanager.com/gtag/js?id=GA_ID'></script>\n\nIn AEM: Use Cloud Service configurations, OSGi services, or Sling servlets." },
    { q: "Do you have experience working with Angular?", a: "Angular knowledge includes:\n\n• TypeScript-based framework by Google\n• Components, Services, Modules architecture\n• Two-way data binding [(ngModel)]\n• Dependency Injection\n• Angular CLI for scaffolding\n• Routing and navigation\n• Reactive Forms and Template-driven Forms\n• HTTP Client for API calls\n• RxJS Observables\n• Directives (structural & attribute)\n• Pipes for data transformation\n• Lifecycle hooks (ngOnInit, ngOnDestroy)" },
    { q: "Have you used any Tools?", a: "Development tools used:\n\n• VS Code: Code editor\n• Chrome DevTools: Debugging\n• Git/GitHub: Version control\n• JIRA: Project management\n• Postman: API testing\n• npm/Yarn: Package managers\n• Webpack: Module bundler\n• Babel: JavaScript compiler\n• ESLint/Prettier: Code quality\n• Figma/Adobe XD: Design reference\n• Jenkins: CI/CD pipeline\n• CRXDE Lite: AEM development\n• AEM Package Manager: Deployment" },
    { q: "What are the features of SCSS?", a: "SCSS (Sassy CSS) features:\n\n1. Variables: $color: #6c5ce7;\n2. Nesting: .parent { .child { } }\n3. Mixins: @mixin flex { display: flex; }\n4. Partials: _variables.scss\n5. Import: @import 'variables';\n6. Inheritance: @extend .class;\n7. Functions: @function calculate($val) { @return $val * 2; }\n8. Operators: width: 100% / 3;\n9. Loops: @for $i from 1 through 3 { }\n10. Conditionals: @if $theme == dark { }\n11. Maps: $colors: (primary: #6c5ce7);" },
    { q: "Any experience working with AEM?", a: "AEM (Adobe Experience Manager) experience:\n\n• Creating custom components with HTL/Sightly\n• Building editable and static templates\n• Working with Client Libraries (CSS/JS)\n• Dialog development (Touch UI)\n• CRXDE Lite for development\n• Content Fragment and Experience Fragment\n• Dispatcher configuration\n• Multi-site management (MSM)\n• Style System and policies\n• Sling Models for backend logic\n• OSGi configurations\n• Package deployment via Maven\n• Working with DAM (Digital Asset Manager)" }
  ]);

  console.log('\n🎉 Batch 1 done! (HUMANA, BAT, GSK)');
}

run().catch(console.error);
