const BASE = 'http://localhost:3000';
let token = '';
const headers = () => ({ 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token });
async function login() { const r = await fetch(`${BASE}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'admin', password: '1234' }) }); const d = await r.json(); token = d.token; }
async function addTopic(name) { const r = await fetch(`${BASE}/api/topics`, { method: 'POST', headers: headers(), body: JSON.stringify({ name }) }); const d = await r.json(); console.log('📁', name); return d.id; }
async function addQ(topicId, q, a) { await fetch(`${BASE}/api/questions`, { method: 'POST', headers: headers(), body: JSON.stringify({ topicId, question: q, answer: a }) }); }

async function run() {
  await login();

  // Merk ACCOUNT
  let id = await addTopic('Merk ACCOUNT');
  await addQ(id, "What is the purpose of ClientLibs in AEM?", "ClientLibs (Client Libraries) in AEM manage and optimize CSS and JS files.\n\nPurpose:\n• Bundle multiple files into a single file\n• Minify CSS/JS for performance\n• Manage dependencies between scripts\n• Keep client-side code organized\n• Allow component-specific or global inclusion\n\nThey help organize resources by categorizing them (using the 'categories' property) and managing load order.");
  await addQ(id, "What are the different methods for creating ClientLibraries?", "Methods to create ClientLibs:\n\n1. Component-level: Create a clientlibs folder inside the component node.\n2. Global/Design-level: Create in /apps/myproject/clientlibs/\n3. ui.frontend module: Modern approach using Webpack to bundle React/Angular/SCSS and auto-generate clientlibs via AEM front-end plugin.\n\nStructure:\n• cq:ClientLibraryFolder node\n• categories (String[])\n• dependencies (String[])\n• embed (String[])\n• js.txt and css.txt (manifest files)");
  await addQ(id, "How do you include ClientLibraries in an AEM page?", "Using HTL (Sightly):\n\n1. Include CSS only:\n<sly data-sly-use.clientlib=\"/libs/granite/sightly/templates/clientlib.html\">\n  <sly data-sly-call=\"${clientlib.css @ categories='my.category'}\"/>\n</sly>\n\n2. Include JS only:\n<sly data-sly-call=\"${clientlib.js @ categories='my.category'}\"/>\n\n3. Include ALL (CSS & JS):\n<sly data-sly-call=\"${clientlib.all @ categories='my.category'}\"/>");
  await addQ(id, "How would you integrate a React application with AEM?", "Steps to integrate React (ui.frontend) with AEM:\n\n1. Create AEM project using Archetype (includes ui.frontend module).\n2. Write React code in ui.frontend/src.\n3. Build process (Webpack) compiles React into pure JS/CSS.\n4. aem-clientlib-generator plugin moves the compiled files into ui.apps/src/main/content/jcr_root/apps/.../clientlibs.\n5. Include the generated clientlib category in the AEM page component.\n6. For SPA Editor routing, use the @adobe/aem-react-editable-components package to map React components to AEM components.");
  await addQ(id, "What is hoisting in JavaScript?", "Hoisting is JS's default behavior of moving declarations to the top of their scope before code execution.\n\n• var: Hoisted and initialized with 'undefined'.\n  console.log(x); // undefined\n  var x = 5;\n\n• let/const: Hoisted but NOT initialized (Temporal Dead Zone).\n  console.log(y); // ReferenceError\n  let y = 10;\n\n• Function Declarations: Completely hoisted.\n  greet(); // Works\n  function greet() { console.log('Hi'); }\n\n• Function Expressions: Treated like variables (not hoisted).");
  await addQ(id, "What is a closure in JavaScript?", "A closure is a function bundled with references to its surrounding state (lexical environment).\n\nIt allows an inner function to access an outer function's scope even after the outer function has returned.\n\nExample:\nfunction makeCounter() {\n  let count = 0; // Private variable\n  return function() {\n    return ++count;\n  };\n}\nconst counter = makeCounter();\nconsole.log(counter()); // 1\nconsole.log(counter()); // 2\n\nUse case: Data privacy, factory functions, event handlers.");
  await addQ(id, "How to Make Optimized JavaScript?", "Best practices for JS optimization:\n\n1. Minification & Bundling (Webpack, Terser)\n2. Tree Shaking (remove unused code)\n3. Lazy Loading & Code Splitting (load JS only when needed)\n4. Debouncing & Throttling for scroll/resize events\n5. Use Web Workers for heavy background tasks\n6. Defer/Async attributes for script tags\n7. Caching via Service Workers\n8. Avoid memory leaks (clean up event listeners)\n9. Use requestAnimationFrame for animations\n10. Optimize loops and avoid deep DOM manipulation");
  await addQ(id, "Difference Between SCSS & Less?", "SCSS and Less are CSS preprocessors.\n\nSCSS (Sass):\n• Syntax: Uses standard CSS syntax + features.\n• Variables: Uses $ ($color: red;)\n• Mixins: @mixin name {} and @include name;\n• Compilation: Originally Ruby, now Dart/C++ (node-sass/dart-sass)\n• Logic: Better support for complex logic (loops, functions)\n\nLess:\n• Variables: Uses @ (@color: red;)\n• Mixins: .name {} and .name();\n• Compilation: JavaScript-based\n• Logic: Simpler, less robust control flow\n\nIndustry trend: SCSS is heavily preferred.");
  await addQ(id, "What is a Promise in JavaScript?", "A Promise handles asynchronous operations.\n\nStates: Pending, Fulfilled, Rejected.\n\nExample:\nconst fetchData = new Promise((resolve, reject) => {\n  let success = true;\n  if (success) resolve('Data loaded');\n  else reject('Error');\n});\n\nfetchData\n  .then(data => console.log(data))\n  .catch(error => console.error(error))\n  .finally(() => console.log('Done'));\n\nPromises solve 'callback hell' by allowing chaining.");
  await addQ(id, "Async and Sync, $fetch()?", "Sync vs Async:\n• Synchronous: Code executes line-by-line, blocking subsequent code until finished.\n• Asynchronous: Non-blocking, allows execution to continue while waiting for operations (like network requests) to finish.\n\nfetch() (or $fetch in Nuxt/Nitro):\n• Facilitates async data fetching using Promises.\n\nExample:\nasync function getUser() {\n  try {\n    const response = await fetch('/api/user');\n    const data = await response.json();\n    console.log(data);\n  } catch (err) {\n    console.error(err);\n  }\n}");
  await addQ(id, "What is data-sly-attribute?", "data-sly-attribute sets HTML attributes dynamically in HTL.\n\nExample:\n<div data-sly-attribute.title=\"${properties.jcr:title}\">Hello</div>\n\nOutput if title is 'Greeting':\n<div title=\"Greeting\">Hello</div>\n\nTo apply multiple attributes from a map:\n<div data-sly-attribute=\"${myAttributesMap}\"></div>");
  await addQ(id, "What is data-sly-list vs Repeat?", "Both are used for iteration in HTL.\n\ndata-sly-list:\n• Does NOT repeat the host element.\n• Repeats the CONTENT inside the element.\n<ul data-sly-list=\"${items}\">\n  <li>${item}</li>\n</ul>\n\ndata-sly-repeat:\n• Repeats the HOST element itself multiple times.\n<div data-sly-repeat=\"${items}\">${item}</div>\n\nBoth expose standard variables: item, itemList.index, itemList.count, etc.");
  await addQ(id, "Dependency vs Embed in ClientLibs?", "Dependencies vs Embed in AEM ClientLibs:\n\ndependencies: [\"other.clientlib\"]\n• Links the other clientlib BEFORE this one.\n• Results in multiple HTTP requests (one for dependency, one for this).\n• Good for shared libraries like jQuery.\n\nembed: [\"other.clientlib\"]\n• Physically MERGES the code of the other clientlib into this one.\n• Results in a single HTTP request.\n• Good for minimizing requests, but reduces cache efficiency if the embedded library is used elsewhere.");
  await addQ(id, "What is data-sly-template?", "data-sly-template defines a reusable HTL block (like a function/macro).\n\nDefinition:\n<template data-sly-template.card=\"${@ title, desc}\">\n  <div class=\"card\">\n    <h2>${title}</h2>\n    <p>${desc}</p>\n  </div>\n</template>\n\nCalling it:\n<sly data-sly-call=\"${card @ title='My Title', desc='My Desc'}\" />");
  await addQ(id, "How to call Model in AEM using sightly?", "Use data-sly-use to call a Sling Model.\n\nHTL:\n<sly data-sly-use.model=\"com.project.core.models.MyModel\">\n  <h1>${model.title}</h1>\n  <p>${model.description}</p>\n</sly>\n\nThe Java Model class needs @Model(adaptables = Resource.class) or SlingHttpServletRequest.class.");
  await addQ(id, "What is event delegation and its example?", "Event delegation is attaching a single event listener to a parent element to handle events for its children (even dynamically added ones).\n\nWhy? Saves memory, handles dynamic elements.\n\nExample:\ndocument.getElementById('parent-list').addEventListener('click', function(e) {\n  if(e.target && e.target.nodeName == 'LI') {\n    console.log('List item clicked: ', e.target.id);\n  }\n});");
  await addQ(id, "What is debouncing and its example?", "Debouncing ensures a function is only executed after a certain amount of time has passed since it was LAST called. Good for search inputs.\n\nExample:\nfunction debounce(func, delay) {\n  let timeoutId;\n  return function(...args) {\n    clearTimeout(timeoutId);\n    timeoutId = setTimeout(() => func.apply(this, args), delay);\n  };\n}\n\nconst handleSearch = debounce((query) => {\n  console.log('Searching for:', query);\n}, 500);");
  console.log('  ✅ Merk ACCOUNT done');

  // AGCOaccount
  id = await addTopic('AGCOaccount');
  await addQ(id, "Difference between display inline and block?", "Block elements:\n• Start on a new line\n• Take up full width available\n• Can have width/height\n• Examples: <div>, <p>, <h1>, <section>\n\nInline elements:\n• Do not start on a new line\n• Take up only necessary width\n• Cannot have width/height applied directly\n• Examples: <span>, <a>, <strong>, <img>");
  await addQ(id, "Explain display: flex", "Flexbox is a 1-dimensional layout model.\n\nKey Concepts:\n• Container: display: flex;\n• Direction: flex-direction (row, column)\n• Main Axis Alignment: justify-content (center, space-between)\n• Cross Axis Alignment: align-items (center, stretch)\n• Wrapping: flex-wrap (wrap, nowrap)\n\nIt makes aligning items (like vertically centering) and distributing space extremely easy.");
  await addQ(id, "What are the datatypes in JS?", "Primitive Types (Value):\n1. String\n2. Number\n3. Boolean\n4. Undefined\n5. Null\n6. Symbol\n7. BigInt\n\nNon-Primitive Types (Reference):\n1. Object (includes Arrays, Functions, Dates)");
  await addQ(id, "Syntax of onClick in A TAG and href purpose?", "Anchor tag with onClick:\n<a href=\"https://example.com\" onClick=\"handleClick(event)\">Click Me</a>\n\nPurpose of href:\n• Defines the destination URL.\n• Essential for accessibility and SEO.\n\nIf you want to prevent the default navigation when clicking:\nfunction handleClick(e) {\n  e.preventDefault();\n  // custom logic\n}");
  await addQ(id, "What is the difference between local storage and session storage?", "Both store key-value string data in the browser.\n\nLocal Storage:\n• Persistent: Data remains even if browser is closed/restarted.\n• Must be manually cleared.\n• Size: ~5MB per domain.\n\nSession Storage:\n• Temporary: Data is cleared when the specific browser tab/window is closed.\n• Size: ~5MB per domain.\n\nBoth are client-side only (not sent with server requests like cookies).");
  await addQ(id, "What is AEM templates and folder structure in CRXDE?", "AEM Templates:\nBlueprints for creating pages. Editable templates are configured by authors/super-users using policies, while Static templates are built by developers.\n\nCRXDE Folder Structure:\n• /apps: Project code (components, templates, clientlibs)\n• /content: Authorable page content and assets\n• /conf: Configurations (Editable templates, policies)\n• /libs: Out-of-the-box AEM code (do not modify!)\n• /etc: Legacy configs, tools, clientlibs\n• /var: Runtime data, logs, audits");
  await addQ(id, "Global and block scope?", "Global Scope:\n• Variables declared outside any function/block.\n• Accessible from anywhere in the file.\n• var, let, const at top level.\n\nBlock Scope:\n• Variables declared inside a { } block (like if, for, while).\n• ONLY accessible within that block.\n• let and const are block-scoped.\n• var is NOT block-scoped (it ignores the block).");
  await addQ(id, "How to target the 3rd button inside a div?", "Using CSS:\ndiv button:nth-child(3) {\n  color: red;\n}\n\nUsing jQuery:\n$('div button:eq(2)').css('color', 'red'); \n// eq() is 0-indexed, so 2 means the 3rd element.\n\nOr simply by giving the 3rd button an ID: <button id=\"btn3\">\n$('#btn3').click();");
  console.log('  ✅ AGCOaccount done');

  // PEARSON ACCOUNT
  id = await addTopic('PEARSON ACCOUNT');
  await addQ(id, "Diff bw == and === operator?", "== (Loose Equality):\n• Compares values AFTER type coercion.\n• Example: 5 == '5' is true.\n\n=== (Strict Equality):\n• Compares BOTH value and type.\n• No type coercion happens.\n• Example: 5 === '5' is false.\n\nBest practice: Always use === to avoid unexpected bugs.");
  await addQ(id, "How to create an array and delete an array element?", "Create array:\nconst fruits = ['apple', 'banana', 'orange'];\n\nDelete element:\n1. splice() (modifies original, removes completely):\n   fruits.splice(1, 1); // removes 'banana'\n\n2. filter() (returns new array):\n   const newArr = fruits.filter(f => f !== 'banana');\n\n3. pop() / shift() (removes last / first item)\n\n4. delete keyword (NOT recommended, leaves 'undefined' hole):\n   delete fruits[1];");
  await addQ(id, "How to create and delete a cookie? Syntax", "Create a cookie:\ndocument.cookie = \"username=John Doe; expires=Thu, 18 Dec 2025 12:00:00 UTC; path=/\";\n\nDelete a cookie (Set expiry date to the past):\ndocument.cookie = \"username=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/\";");
  await addQ(id, "Static and editable template difference", "Static Templates:\n• Created by developers in CRXDE (/apps).\n• Structure is fixed via page components.\n• Requires developer deployment to change structure.\n\nEditable Templates:\n• Created by authors/super-users via UI (Tools > Templates).\n• Stored in /conf.\n• Uses dynamic layout container and policies.\n• Authors can add/remove components from the template structure without developer help.");
  await addQ(id, "Experience & Content fragment uses.", "Content Fragment (CF):\n• Pure text/data (headless content).\n• Channel-agnostic (can be used on web, mobile app, IoT).\n• Based on Content Fragment Models (schema).\n• Great for articles, product data.\n\nExperience Fragment (XF):\n• Group of components + layout + styling.\n• Defines a visual 'experience'.\n• Can be reused across pages (e.g., Headers, Footers, Promos).\n• Can be exported to Adobe Target for personalization.");
  await addQ(id, "Apply color based on the below selectors", "1. div p: Descendant selector. Targets ALL <p> inside <div>.\n2. div, p: Grouping. Targets ALL <div> AND ALL <p>.\n3. div > p: Child selector. Targets <p> that are DIRECT children of <div>.\n4. div + p: Adjacent sibling. Targets the FIRST <p> immediately following a <div>.\n5. div ~ p: General sibling. Targets ALL <p> that follow a <div> sharing the same parent.");
  console.log('  ✅ PEARSON ACCOUNT done');

  console.log('\n🎉 Batch 3 done!');
}
run().catch(console.error);
