const BASE = 'http://localhost:3000';
let token = '';
const headers = () => ({ 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token });
async function login() { const r = await fetch(`${BASE}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'admin', password: '1234' }) }); const d = await r.json(); token = d.token; }
async function addTopic(name) { const r = await fetch(`${BASE}/api/topics`, { method: 'POST', headers: headers(), body: JSON.stringify({ name }) }); const d = await r.json(); console.log('📁', name); return d.id; }
async function addQ(topicId, q, a) { await fetch(`${BASE}/api/questions`, { method: 'POST', headers: headers(), body: JSON.stringify({ topicId, question: q, answer: a }) }); }

async function run() {
  await login();

  // AZ Account
  let id = await addTopic('AZ Account');
  await addQ(id, "Remove negative values from array?", "Use the filter() method:\n\nlet arr = [10, 20, -30, 40, 60, -90];\nlet positive = arr.filter(num => num >= 0);\nconsole.log(positive); // [10, 20, 40, 60]\n\nfilter() creates a new array with elements that pass the test condition.");
  await addQ(id, "Write a single function for sum(2,3) and sum(2)(3)?", "function sum(a, b) {\n  if (b !== undefined) return a + b;\n  return function(b) { return a + b; };\n}\n\nconsole.log(sum(2, 3)); // 5\nconsole.log(sum(2)(3)); // 5\n\nThis uses currying — if b is provided, return sum directly. Otherwise return a function that accepts b.");
  await addQ(id, "What is the use of Promises?", "Promises handle asynchronous operations in JavaScript.\n\nStates:\n• Pending: Initial state\n• Fulfilled: Operation completed\n• Rejected: Operation failed\n\nExample:\nconst promise = new Promise((resolve, reject) => {\n  setTimeout(() => resolve('Done!'), 1000);\n});\npromise.then(result => console.log(result));\n\nUsed for: API calls, file reading, timers, database queries.");
  await addQ(id, "What is site level configuration in AEM?", "Site level configuration in AEM defines settings applied across an entire site:\n\n• Context-Aware Configuration (Sling CA Config)\n• Stored under /conf/site-name/\n• Includes: Templates, policies, cloud configs\n• Editable Templates policies\n• Language and locale settings\n• Cloud Service configurations\n• SEO configurations\n• Navigation structure settings\n\nAccess via: Tools > Configuration Browser");
  await addQ(id, "What is SLY and how to loop for component?", "SLY is the HTL (Sightly) tag used in AEM for logic without rendering extra HTML.\n\nLoop example:\n<sly data-sly-list.item=\"${itemList}\">\n  <div>${item.title}</div>\n</sly>\n\nRepeat example:\n<div data-sly-repeat.item=\"${itemList}\">\n  ${item.title}\n</div>\n\nDifference: data-sly-list doesn't render the host element, data-sly-repeat does.");
  await addQ(id, "What are the properties used in sly tag?", "HTL (Sightly) data-sly properties:\n\n• data-sly-use: Initialize Java/JS objects\n• data-sly-list: Iterate without host element\n• data-sly-repeat: Iterate with host element\n• data-sly-test: Conditional rendering\n• data-sly-attribute: Set HTML attributes\n• data-sly-element: Change element tag\n• data-sly-text: Set text content\n• data-sly-set: Declare variables\n• data-sly-template: Define reusable templates\n• data-sly-call: Call templates\n• data-sly-resource: Include components\n• data-sly-include: Include scripts");
  await addQ(id, "How to declare variables and write conditionals in sly?", "Declaring variables:\n<sly data-sly-set.myVar=\"${'Hello'}\" />\n<p>${myVar}</p>\n\nConditional statements:\n<sly data-sly-test=\"${currentPage.title}\">\n  <h1>${currentPage.title}</h1>\n</sly>\n\n<sly data-sly-test.hasTitle=\"${currentPage.title}\">\n  <h1>${currentPage.title}</h1>\n</sly>\n<sly data-sly-test=\"${!hasTitle}\">\n  <h1>Default Title</h1>\n</sly>");
  await addQ(id, "Flex columns on desktop, rows on mobile?", "Use CSS Flexbox with media queries:\n\n.parent {\n  display: flex;\n  flex-direction: row; /* columns side by side on desktop */\n  gap: 16px;\n}\n\n.child {\n  flex: 1;\n}\n\n@media (max-width: 768px) {\n  .parent {\n    flex-direction: column; /* stacked as rows on mobile */\n  }\n}\n\nThis makes 3 child divs appear as columns on desktop and stack vertically on mobile.");
  console.log('  ✅ AZ done');

  // Merck Front-End
  id = await addTopic('Merck Front-End');
  await addQ(id, "What are rest and spread operators?", "Spread (...) expands elements:\nconst arr = [1, 2, 3];\nconst newArr = [...arr, 4, 5]; // [1,2,3,4,5]\nconst obj = { ...oldObj, newProp: 'val' };\n\nRest (...) collects elements:\nfunction sum(...nums) {\n  return nums.reduce((a, b) => a + b);\n}\nconst [first, ...rest] = [1, 2, 3]; // first=1, rest=[2,3]");
  await addQ(id, "What are closures?", "A closure is a function that has access to its outer function's variables even after the outer function has returned.\n\nExample:\nfunction outer() {\n  let count = 0;\n  return function inner() {\n    count++;\n    return count;\n  };\n}\nconst counter = outer();\nconsole.log(counter()); // 1\nconsole.log(counter()); // 2\n\nUse cases: Data privacy, factory functions, callbacks, memoization.");
  await addQ(id, "What is a Promise?", "A Promise represents the eventual completion or failure of an async operation.\n\nconst promise = new Promise((resolve, reject) => {\n  // async operation\n  if (success) resolve(data);\n  else reject(error);\n});\n\npromise\n  .then(data => console.log(data))\n  .catch(err => console.error(err))\n  .finally(() => console.log('Done'));\n\nStates: Pending → Fulfilled or Rejected\nChaining: .then().then().catch()");
  await addQ(id, "What is lexical scope?", "Lexical scope means a function's scope is determined by where it is written in the code, not where it is called.\n\nExample:\nfunction outer() {\n  const x = 10;\n  function inner() {\n    console.log(x); // 10 — accesses outer's scope\n  }\n  inner();\n}\n\nInner functions can access variables from outer functions. This is the foundation of closures.");
  await addQ(id, "What are CSS positions and differences?", "CSS position values:\n\n• static: Default, normal document flow\n• relative: Positioned relative to its normal position\n• absolute: Positioned relative to nearest positioned ancestor\n• fixed: Positioned relative to viewport, stays on scroll\n• sticky: Toggles between relative and fixed based on scroll\n\nKey differences:\n• static/relative stay in document flow\n• absolute/fixed are removed from flow\n• sticky is hybrid — relative until scroll threshold");
  await addQ(id, "What is a framework?", "A framework is a pre-built structure providing tools, libraries, and conventions for building applications.\n\nExamples:\n• Angular: Full frontend framework\n• React: UI library (often called framework)\n• Vue.js: Progressive framework\n• Express: Node.js backend framework\n\nFramework vs Library:\n• Framework: Controls flow (calls your code)\n• Library: You control flow (you call it)\n\nBenefits: Faster development, best practices, community support, maintainability.");
  await addQ(id, "Difference between template and component in AEM?", "Template:\n• Defines page structure and layout\n• Blueprint for creating pages\n• Contains allowed components, policies\n• Located in /conf/ (editable) or /apps/ (static)\n\nComponent:\n• Reusable content building block\n• Has dialog, HTL, CSS, JS\n• Renders specific content (text, image, carousel)\n• Located in /apps/project/components/\n\nRelationship: A template uses components to build pages.");
  await addQ(id, "Difference between Authentication and Authorization?", "Authentication: Verifying WHO you are\n• Login with username/password\n• JWT tokens, OAuth\n• Proves identity\n\nAuthorization: Verifying WHAT you can access\n• Role-based access (admin, user)\n• Permissions (read, write, delete)\n• Happens AFTER authentication\n\nExample:\n• Authentication: Logging into a website\n• Authorization: Admin can delete users, regular user cannot");
  await addQ(id, "Security measures for creating a site?", "Security measures:\n\n• HTTPS/SSL encryption\n• Input validation and sanitization\n• XSS prevention (escape user input)\n• CSRF tokens\n• Content Security Policy (CSP) headers\n• Secure authentication (JWT, OAuth)\n• Password hashing (bcrypt)\n• Rate limiting\n• CORS configuration\n• SQL injection prevention\n• Regular security audits\n• OWASP guidelines compliance\n• HTTP-only cookies\n• Secure headers (X-Frame-Options, X-XSS-Protection)");
  await addQ(id, "What is useStrict in JS?", "'use strict' enables strict mode in JavaScript.\n\nBenefits:\n• Prevents undeclared variables\n• Throws errors for unsafe actions\n• Disallows duplicate parameters\n• Makes 'this' undefined in functions (not window)\n• Prevents deleting variables\n\nUsage:\n'use strict';\nx = 10; // ❌ Error: x is not defined\n\nvar x = 10; // ✅ Works\n\nES6 modules are automatically in strict mode.");
  await addQ(id, "What are arrow functions?", "Arrow functions are a shorter syntax for writing functions (ES6).\n\nSyntax:\nconst add = (a, b) => a + b;\nconst greet = name => `Hello ${name}`;\nconst getObj = () => ({ key: 'value' });\n\nDifferences from regular functions:\n• No own 'this' (inherits from parent scope)\n• No 'arguments' object\n• Cannot be used as constructors\n• Cannot be used with 'new'\n• Shorter syntax\n• Implicit return for single expressions");
  console.log('  ✅ Merck done');

  // NNI Account
  id = await addTopic('NNI Account');
  await addQ(id, "Difference between class & functional component?", "Class Component:\n• ES6 class extending React.Component\n• Has lifecycle methods\n• Uses this.state and this.setState\n• More verbose\n\nFunctional Component:\n• Simple JavaScript function\n• Uses Hooks (useState, useEffect)\n• Shorter and cleaner\n• Better performance\n• Easier to test\n\nModern React prefers functional components with Hooks.");
  await addQ(id, "Explain useEffect with dependencies?", "useEffect(callback, dependencies):\n\n1. No dependency: Runs on every render\nuseEffect(() => { }); \n\n2. Empty array: Runs once on mount\nuseEffect(() => { }, []);\n\n3. With dependencies: Runs when values change\nuseEffect(() => {\n  fetchData(userId);\n}, [userId]);\n\n4. Cleanup: Return function runs on unmount\nuseEffect(() => {\n  const timer = setInterval(fn, 1000);\n  return () => clearInterval(timer);\n}, []);");
  await addQ(id, "Explain Props Drilling?", "Props drilling is passing data through multiple component levels even when intermediate components don't need it.\n\nProblem:\nApp → Parent → Child → GrandChild\n(data passes through Parent and Child just to reach GrandChild)\n\nSolutions:\n• Context API: React.createContext()\n• Redux/Zustand: Global state management\n• Component composition\n• Custom hooks\n\nContext API example:\nconst MyContext = createContext();\n<MyContext.Provider value={data}>\n  <GrandChild /> // can access data directly\n</MyContext.Provider>");
  await addQ(id, "Explain 'this' scope in class-based component?", "'this' in class components refers to the component instance.\n\nProblem: 'this' is undefined in event handlers.\nSolution: Bind in constructor or use arrow functions.\n\nclass App extends React.Component {\n  constructor() {\n    super();\n    this.handleClick = this.handleClick.bind(this); // Method 1\n  }\n  handleClick() { console.log(this.state); }\n  \n  // Method 2: Arrow function\n  handleClick = () => { console.log(this.state); }\n}");
  await addQ(id, "What is Redux?", "Redux is a predictable state management library.\n\nCore concepts:\n• Store: Single source of truth\n• Actions: Describe what happened\n• Reducers: Pure functions that update state\n• Dispatch: Send actions to store\n\nFlow: UI → dispatch(action) → reducer → new state → UI updates\n\nExample:\nconst reducer = (state = 0, action) => {\n  switch(action.type) {\n    case 'INCREMENT': return state + 1;\n    default: return state;\n  }\n};");
  await addQ(id, "What is useContext?", "useContext is a React Hook to consume Context values without prop drilling.\n\nconst ThemeContext = createContext('dark');\n\n// Provider\n<ThemeContext.Provider value='light'>\n  <App />\n</ThemeContext.Provider>\n\n// Consumer (using Hook)\nfunction App() {\n  const theme = useContext(ThemeContext);\n  return <div className={theme}>Hello</div>;\n}\n\nBenefits: Avoids prop drilling, simpler than Redux for simple state.");
  await addQ(id, "What is Webpack?", "Webpack is a module bundler for JavaScript applications.\n\nFeatures:\n• Bundles JS, CSS, images into single/few files\n• Code splitting and lazy loading\n• Tree shaking (removes unused code)\n• Hot Module Replacement (HMR)\n• Loaders: Transform files (babel-loader, css-loader)\n• Plugins: Extend functionality\n• Dev server with live reload\n• Source maps for debugging\n• Minification and optimization");
  await addQ(id, "What is a Closure?", "A closure is a function bundled with its lexical environment.\n\nfunction createCounter() {\n  let count = 0;\n  return {\n    increment: () => ++count,\n    getCount: () => count\n  };\n}\nconst counter = createCounter();\ncounter.increment();\nconsole.log(counter.getCount()); // 1\n\nThe inner functions 'remember' the count variable even after createCounter finishes.");
  await addQ(id, "What is Sass mixin?", "A Sass mixin is a reusable block of styles.\n\n@mixin flexCenter($direction: row) {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n  flex-direction: $direction;\n}\n\n.container {\n  @include flexCenter(column);\n}\n\nWith content block:\n@mixin responsive($breakpoint) {\n  @media (max-width: $breakpoint) { @content; }\n}\n.box {\n  @include responsive(768px) { width: 100%; }\n}");
  await addQ(id, "How to find typeof an object?", "Methods to check type:\n\n• typeof: Returns type as string\n  typeof 'hello' // 'string'\n  typeof 42 // 'number'\n  typeof {} // 'object'\n  typeof [] // 'object' (⚠️ arrays are objects)\n\n• Array.isArray(): Check arrays\n  Array.isArray([1,2]) // true\n\n• instanceof: Check constructor\n  obj instanceof Array // true\n\n• Object.prototype.toString.call():\n  Object.prototype.toString.call([]) // '[object Array]'");
  await addQ(id, "preventDefault vs stopPropagation?", "event.preventDefault():\n• Prevents the default browser action\n• Example: Stops form submission, link navigation\n\nevent.stopPropagation():\n• Stops event from bubbling up to parent elements\n• Example: Click on child doesn't trigger parent's click\n\nExample:\n<a href='/page' onClick={(e) => {\n  e.preventDefault(); // won't navigate\n  e.stopPropagation(); // won't trigger parent click\n}}>Link</a>");
  await addQ(id, "What is Mutation Observer in JS?", "MutationObserver watches for DOM changes.\n\nconst observer = new MutationObserver((mutations) => {\n  mutations.forEach(m => console.log(m.type));\n});\n\nobserver.observe(document.body, {\n  childList: true, // watch child additions/removals\n  attributes: true, // watch attribute changes\n  subtree: true // watch all descendants\n});\n\n// Stop observing\nobserver.disconnect();\n\nUse cases: Dynamic content tracking, DOM change detection, accessibility tools.");
  await addQ(id, "What is the Event Loop?", "The Event Loop manages asynchronous operations in JavaScript.\n\nFlow:\n1. Call Stack: Executes synchronous code\n2. Web APIs: Handle async operations (setTimeout, fetch)\n3. Callback Queue: Stores callbacks from Web APIs\n4. Microtask Queue: Promises (.then callbacks)\n5. Event Loop: Moves tasks to Call Stack when empty\n\nPriority: Microtasks (Promises) > Macrotasks (setTimeout)\n\nconsole.log('1');\nsetTimeout(() => console.log('2'), 0);\nPromise.resolve().then(() => console.log('3'));\nconsole.log('4');\n// Output: 1, 4, 3, 2");
  await addQ(id, "What is display: flex?", "display: flex creates a flex container for flexible layouts.\n\nProperties:\n• flex-direction: row | column\n• justify-content: center | space-between | flex-start\n• align-items: center | stretch | flex-start\n• flex-wrap: wrap | nowrap\n• gap: spacing between items\n\nChild properties:\n• flex-grow, flex-shrink, flex-basis\n• align-self\n• order\n\n.container {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}");
  await addQ(id, "What is Event Listener?", "addEventListener attaches an event handler to an element.\n\nSyntax:\nelement.addEventListener(event, handler, options);\n\nExample:\nbutton.addEventListener('click', (e) => {\n  console.log('Clicked!', e.target);\n});\n\nCommon events: click, input, submit, keydown, mouseover, scroll, load\n\nRemove listener:\nbutton.removeEventListener('click', handler);\n\n3rd parameter options:\n{ once: true } — runs once\n{ capture: true } — capture phase");
  await addQ(id, "What is splice method?", "splice() modifies an array by adding/removing elements in place.\n\nSyntax: array.splice(start, deleteCount, ...items)\n\nRemove:\nlet arr = [1,2,3,4,5];\narr.splice(2, 1); // removes index 2\n// arr = [1,2,4,5]\n\nInsert:\narr.splice(2, 0, 'a', 'b');\n// arr = [1,2,'a','b',4,5]\n\nReplace:\narr.splice(1, 2, 'x');\n// replaces 2 items at index 1\n\nReturns: Array of removed elements\nNote: Mutates the original array (unlike slice).");
  await addQ(id, "Explain about AEM?", "AEM (Adobe Experience Manager) is a comprehensive CMS for building websites, mobile apps, and forms.\n\nKey features:\n• Component-based architecture\n• WYSIWYG author editing\n• Templates and page management\n• Digital Asset Management (DAM)\n• Content Fragments and Experience Fragments\n• Multi-site management (MSM)\n• Workflows and approvals\n• Dispatcher for caching\n• Cloud-ready with AEM as a Cloud Service\n• Integration with Adobe Analytics, Target\n• Built on Apache Sling, JCR, OSGi");
  console.log('  ✅ NNI done');

  console.log('\n🎉 Batch 2 done! (AZ, Merck, NNI)');
}
run().catch(console.error);
