const BASE = 'http://localhost:3000';
let token = '';
const headers = () => ({ 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + token });
async function login() { const r = await fetch(`${BASE}/api/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: 'admin', password: '1234' }) }); const d = await r.json(); token = d.token; }
async function addTopic(name) { const r = await fetch(`${BASE}/api/topics`, { method: 'POST', headers: headers(), body: JSON.stringify({ name }) }); const d = await r.json(); console.log('📁', name); return d.id; }
async function addQ(topicId, q, a) { await fetch(`${BASE}/api/questions`, { method: 'POST', headers: headers(), body: JSON.stringify({ topicId, question: q, answer: a }) }); }

async function run() {
  await login();

  // Spring Boot & Database Account
  let id = await addTopic('Spring Boot & Database Account');
  
  await addQ(id, "What is the lifecycle of a Spring Boot application?", "1. Application Context Creation: Spring container is initialized.\n2. Bean Initialization: Beans are instantiated, properties populated, and @PostConstruct methods are called.\n3. Application Runner: Command-line runners and ApplicationRunners execute.\n4. Application Running: The app is ready to serve requests.\n5. Application Termination: @PreDestroy methods are called, and the context is closed.");
  await addQ(id, "Key SQL concepts for a frontend developer?", "1. Basic CRUD: SELECT, INSERT, UPDATE, DELETE.\n2. Joins: INNER JOIN, LEFT JOIN (how data from multiple tables is combined).\n3. Filtering & Sorting: WHERE, ORDER BY, LIMIT.\n4. Aggregation: COUNT, SUM, GROUP BY.\n5. Normalization: Understanding how data is split into relational tables to reduce redundancy.");
  await addQ(id, "Communication between two unrelated components in Angular?", "Use a shared Service with RxJS Subjects or BehaviorSubjects.\n\n1. Create a service with a BehaviorSubject.\n2. Component A calls a method in the service to emit a new value to the subject (.next(value)).\n3. Component B subscribes to the subject to react to the new value.");
  await addQ(id, "Reactive forms vs template driven?", "Template-Driven Forms:\n• Defined in HTML using ngModel.\n• Asynchronous.\n• Logic is heavily in the template.\n• Harder to unit test.\n• Good for simple forms.\n\nReactive Forms:\n• Defined in TypeScript using FormControl/FormGroup.\n• Synchronous.\n• Logic is in the component class.\n• Easy to unit test.\n• Good for complex, dynamic forms.");
  await addQ(id, "Signals - use case and methods", "Signals are reactive primitives for fine-grained state updates without Zone.js.\n\nMethods:\n• WritableSignal.set(value): Replaces the value.\n• WritableSignal.update(fn): Updates based on the current value.\n\nUse case: Managing local component state or shared state where you want optimal change detection performance.");
  await addQ(id, "computed() in Angular Signals", "computed() creates a derived signal that automatically updates when its dependent signals change.\n\nExample:\nconst count = signal(0);\nconst doubleCount = computed(() => count() * 2);\n// If count() becomes 2, doubleCount() automatically becomes 4. It is lazily evaluated and memoized.");
  await addQ(id, "Interceptor with examples", "Interceptors intercept HTTP requests/responses.\n\nExample Use Case (Auth Token):\n@Injectable()\nexport class AuthInterceptor implements HttpInterceptor {\n  intercept(req: HttpRequest<any>, next: HttpHandler) {\n    const authReq = req.clone({\n      headers: req.headers.set('Authorization', 'Bearer my-token')\n    });\n    return next.handle(authReq);\n  }\n}");
  await addQ(id, "Is API handling used for performance optimization? How?", "Yes.\n• Caching: Using interceptors or services to cache responses (e.g., shareReplay in RxJS) prevents redundant network calls.\n• Debouncing: Preventing API spam on search inputs.\n• Pagination/Lazy Loading: Only requesting the data currently needed by the user.");
  await addQ(id, "async pipe in Angular", "The `async` pipe subscribes to an Observable or Promise and returns the latest value it has emitted. When the component gets destroyed, the async pipe automatically unsubscribes to avoid memory leaks.\n\nExample:\n<div *ngIf=\"user$ | async as user\">\n  {{ user.name }}\n</div>");
  await addQ(id, "promise vs observable", "Promise:\n• Emits a single value.\n• Not cancellable.\n• Executes immediately upon creation (eager).\n• Best for single async events (e.g., fetch API).\n\nObservable:\n• Emits multiple values over time.\n• Cancellable (via unsubscribe).\n• Lazy (does nothing until subscribed to).\n• Provides powerful operators (map, filter, switchMap).");
  await addQ(id, "Library used for PDF generation, excel export?", "• PDF Generation: pdfmake, jsPDF, or html2pdf.js\n• Excel Export: xlsx (SheetJS), exceljs\n• Dynamic Forms: Formly (Angular)");
  await addQ(id, "Git tag, how to create git tag?", "Git tags are used to mark specific points in history as important (usually releases like v1.0.0).\n\nCreate a lightweight tag:\ngit tag v1.0.0\n\nCreate an annotated tag (recommended):\ngit tag -a v1.0.0 -m \"Release version 1.0.0\"\n\nPush tags to remote:\ngit push origin --tags");
  await addQ(id, "Angular decorators and types", "Decorators attach metadata to classes, methods, or properties.\n\nTypes:\n1. Class Decorators: @Component(), @Directive(), @Pipe(), @Injectable(), @NgModule()\n2. Property Decorators: @Input(), @Output(), @ViewChild(), @ContentChild()\n3. Method Decorators: @HostListener()\n4. Parameter Decorators: @Inject()");
  await addQ(id, "ngTemplate", "<ng-template> defines a template block that is NOT rendered by default. It is only rendered when explicitly instantiated by structural directives (like *ngIf or *ngFor) or dynamically via ViewContainerRef.\n\nExample:\n<div *ngIf=\"isLoggedIn; else loginTpl\">Welcome!</div>\n<ng-template #loginTpl>Please log in.</ng-template>");
  await addQ(id, "Which RXJS operator to use for throttling/debouncing?", "• debounceTime(ms): Emits a value only after a specified time has passed without another emission. (Great for search bars).\n• throttleTime(ms): Emits a value immediately, then ignores subsequent values for a specified duration. (Great for button clicks or scroll events).");
  await addQ(id, "3 API calls, perform action after all 3 completed", "Use RxJS `forkJoin`.\n\nforkJoin([\n  this.http.get('/api/users'),\n  this.http.get('/api/posts'),\n  this.http.get('/api/comments')\n]).subscribe(([users, posts, comments]) => {\n  // This executes only when ALL 3 API calls succeed.\n  console.log('All data loaded');\n});");
  await addQ(id, "Parent to child content sharing (ng-content)", "Content Projection allows passing HTML content from a parent component to a child component.\n\nChild Component (card.component.html):\n<div class=\"card\">\n  <ng-content select=\"[header]\"></ng-content>\n  <ng-content></ng-content> <!-- Default -->\n</div>\n\nParent Component:\n<app-card>\n  <h1 header>My Title</h1>\n  <p>Body text goes here.</p>\n</app-card>");
  await addQ(id, "Angular change detection", "Change detection is how Angular syncs the component state with the UI DOM.\n\nStrategies:\n1. Default: Checks the whole component tree every time an event occurs anywhere.\n2. OnPush: Only checks the component if its @Input references change, an event originates within the component, or an observable linked via async pipe emits.\nOnPush is vastly superior for performance.");
  await addQ(id, "subject vs behaviour subject", "Subject:\n• Does NOT hold an initial value.\n• Late subscribers will NOT get the previous value, only new ones emitted after they subscribe.\n\nBehaviorSubject:\n• REQUIRES an initial value.\n• Always holds the 'current' value.\n• Late subscribers immediately receive the most recent value upon subscribing.");
  await addQ(id, "Destructuring in JS", "Extracting values into separate variables.\n\nObject:\nconst { name, age } = { name: 'John', age: 30 };\n\nArray:\nconst [first, second] = [10, 20];");
  await addQ(id, "void in Typescript", "void is a return type for functions that do not return any value.\n\nExample:\nfunction logMessage(msg: string): void {\n  console.log(msg);\n  // No return statement\n}");
  
  console.log('  ✅ Spring Boot & Database Account done');
  console.log('\n🎉 Batch 7 done!');
}
run().catch(console.error);
